CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE "ThroughputPoints" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Identifier" text NOT NULL,
    "MaximumAircraftPerHour" integer NOT NULL,
    "MaximumSlots" integer NOT NULL,
    "SlotsAllocated" integer NOT NULL,
    "SimulationAnalysisStartTime" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ThroughputPoints" PRIMARY KEY ("Id")
);

CREATE TABLE "VATSIMEvents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "RouteRevision" bigint NOT NULL,
    "SlotRevision" bigint NOT NULL,
    "Date" date NOT NULL,
    "DepartureTimeWindow" interval NOT NULL,
    "CalculationParameters_RecalculateMaximumAirportSlots" boolean NOT NULL,
    "CalculationParameters_IntendedSlotGenerationMode" text NOT NULL,
    "CalculationParameters_SlotGenerationOutputCommentary" text NOT NULL,
    "CalculationParameters_DepartureTimeWindowOffsetSynchronization~" double precision NOT NULL,
    "CalculationParameters_SimulationAnalysisResolution" interval NOT NULL,
    "CalculationParameters_ShouldSimulationUseActualWeatherForecast~" boolean NOT NULL,
    "CalculationParameters_SimulationOutputCommentary" text NOT NULL,
    CONSTRAINT "PK_VATSIMEvents" PRIMARY KEY ("Id")
);

CREATE TABLE "Locations" (
    "Id" integer NOT NULL,
    "Latitude" double precision NOT NULL,
    "Longitude" double precision NOT NULL,
    "VATSIMEventId" integer,
    CONSTRAINT "PK_Locations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Locations_ThroughputPoints_Id" FOREIGN KEY ("Id") REFERENCES "ThroughputPoints" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Locations_VATSIMEvents_VATSIMEventId" FOREIGN KEY ("VATSIMEventId") REFERENCES "VATSIMEvents" ("Id")
);

CREATE TABLE "RouteSegments" (
    "Id" integer NOT NULL,
    "RouteString" text NOT NULL,
    "RouteSegmentGroup" text NOT NULL,
    "RouteSegmentTags" text[] NOT NULL,
    "VATSIMEventId" integer,
    CONSTRAINT "PK_RouteSegments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RouteSegments_ThroughputPoints_Id" FOREIGN KEY ("Id") REFERENCES "ThroughputPoints" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RouteSegments_VATSIMEvents_VATSIMEventId" FOREIGN KEY ("VATSIMEventId") REFERENCES "VATSIMEvents" ("Id")
);

CREATE TABLE "Sectors" (
    "Id" integer NOT NULL,
    "MaxLatitude" double precision NOT NULL,
    "MinLatitude" double precision NOT NULL,
    "MaxLongitude" double precision NOT NULL,
    "MinLongitude" double precision NOT NULL,
    "Coordinates" jsonb NOT NULL,
    "VATSIMEventId" integer,
    CONSTRAINT "PK_Sectors" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sectors_ThroughputPoints_Id" FOREIGN KEY ("Id") REFERENCES "ThroughputPoints" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Sectors_VATSIMEvents_VATSIMEventId" FOREIGN KEY ("VATSIMEventId") REFERENCES "VATSIMEvents" ("Id")
);

CREATE TABLE "Airports" (
    "Id" integer NOT NULL,
    "DepartureTimeWindowStart" timestamp with time zone NOT NULL,
    "NumberOfVotes" integer NOT NULL,
    "VATSIMEventId1" integer,
    CONSTRAINT "PK_Airports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Airports_Locations_Id" FOREIGN KEY ("Id") REFERENCES "Locations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Airports_VATSIMEvents_VATSIMEventId1" FOREIGN KEY ("VATSIMEventId1") REFERENCES "VATSIMEvents" ("Id")
);

CREATE TABLE "RouteSegmentLocations" (
    "LocationsId" integer NOT NULL,
    "RouteSegmentId" integer NOT NULL,
    CONSTRAINT "PK_RouteSegmentLocations" PRIMARY KEY ("LocationsId", "RouteSegmentId"),
    CONSTRAINT "FK_RouteSegmentLocations_Locations_LocationsId" FOREIGN KEY ("LocationsId") REFERENCES "Locations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RouteSegmentLocations_RouteSegments_RouteSegmentId" FOREIGN KEY ("RouteSegmentId") REFERENCES "RouteSegments" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RouteSegmentSectors" (
    "ProvidedFacilityProgressionId" integer NOT NULL,
    "RouteSegmentId" integer NOT NULL,
    CONSTRAINT "PK_RouteSegmentSectors" PRIMARY KEY ("ProvidedFacilityProgressionId", "RouteSegmentId"),
    CONSTRAINT "FK_RouteSegmentSectors_RouteSegments_RouteSegmentId" FOREIGN KEY ("RouteSegmentId") REFERENCES "RouteSegments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RouteSegmentSectors_Sectors_ProvidedFacilityProgressionId" FOREIGN KEY ("ProvidedFacilityProgressionId") REFERENCES "Sectors" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Slots" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "DepartureTime" timestamp with time zone NOT NULL,
    "ProjectedArrivalTime" timestamp with time zone NOT NULL,
    "DepartureAirportId" integer NOT NULL,
    "ArrivalAirportId" integer NOT NULL,
    "ThroughputPointId" integer,
    "VATSIMEventId" integer,
    CONSTRAINT "PK_Slots" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Slots_Airports_ArrivalAirportId" FOREIGN KEY ("ArrivalAirportId") REFERENCES "Airports" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Slots_Airports_DepartureAirportId" FOREIGN KEY ("DepartureAirportId") REFERENCES "Airports" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Slots_ThroughputPoints_ThroughputPointId" FOREIGN KEY ("ThroughputPointId") REFERENCES "ThroughputPoints" ("Id"),
    CONSTRAINT "FK_Slots_VATSIMEvents_VATSIMEventId" FOREIGN KEY ("VATSIMEventId") REFERENCES "VATSIMEvents" ("Id")
);

CREATE TABLE "SlotRouteSegments" (
    "RouteSegmentsId" integer NOT NULL,
    "SlotId" integer NOT NULL,
    CONSTRAINT "PK_SlotRouteSegments" PRIMARY KEY ("RouteSegmentsId", "SlotId"),
    CONSTRAINT "FK_SlotRouteSegments_RouteSegments_RouteSegmentsId" FOREIGN KEY ("RouteSegmentsId") REFERENCES "RouteSegments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SlotRouteSegments_Slots_SlotId" FOREIGN KEY ("SlotId") REFERENCES "Slots" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Airports_VATSIMEventId1" ON "Airports" ("VATSIMEventId1");

CREATE INDEX "IX_Locations_VATSIMEventId" ON "Locations" ("VATSIMEventId");

CREATE INDEX "IX_RouteSegmentLocations_RouteSegmentId" ON "RouteSegmentLocations" ("RouteSegmentId");

CREATE INDEX "IX_RouteSegments_VATSIMEventId" ON "RouteSegments" ("VATSIMEventId");

CREATE INDEX "IX_RouteSegmentSectors_RouteSegmentId" ON "RouteSegmentSectors" ("RouteSegmentId");

CREATE INDEX "IX_Sectors_VATSIMEventId" ON "Sectors" ("VATSIMEventId");

CREATE INDEX "IX_SlotRouteSegments_SlotId" ON "SlotRouteSegments" ("SlotId");

CREATE INDEX "IX_Slots_ArrivalAirportId" ON "Slots" ("ArrivalAirportId");

CREATE INDEX "IX_Slots_DepartureAirportId" ON "Slots" ("DepartureAirportId");

CREATE INDEX "IX_Slots_ThroughputPointId" ON "Slots" ("ThroughputPointId");

CREATE INDEX "IX_Slots_VATSIMEventId" ON "Slots" ("VATSIMEventId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260318183332_InitialCreate', '10.0.5');

COMMIT;

