// <auto-generated />
using System;
using System.Collections.Generic;
using CTPSimulator.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CTPSimulator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CTPSimulator.Slot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArrivalAirportId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartureAirportId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ProjectedArrivalTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ThroughputPointId")
                        .HasColumnType("integer");

                    b.Property<int?>("VATSIMEventId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("DepartureAirportId");

                    b.HasIndex("ThroughputPointId");

                    b.HasIndex("VATSIMEventId");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("CTPSimulator.ThroughputPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaximumAircraftPerHour")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumSlots")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SimulationAnalysisStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SlotsAllocated")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ThroughputPoints", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CTPSimulator.VATSIMEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeSpan>("DepartureTimeWindow")
                        .HasColumnType("interval");

                    b.Property<long>("RouteRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("SlotRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VATSIMEvents");
                });

            modelBuilder.Entity("RouteSegmentLocations", b =>
                {
                    b.Property<int>("LocationsId")
                        .HasColumnType("integer");

                    b.Property<int>("RouteSegmentId")
                        .HasColumnType("integer");

                    b.HasKey("LocationsId", "RouteSegmentId");

                    b.HasIndex("RouteSegmentId");

                    b.ToTable("RouteSegmentLocations");
                });

            modelBuilder.Entity("RouteSegmentSectors", b =>
                {
                    b.Property<int>("ProvidedFacilityProgressionId")
                        .HasColumnType("integer");

                    b.Property<int>("RouteSegmentId")
                        .HasColumnType("integer");

                    b.HasKey("ProvidedFacilityProgressionId", "RouteSegmentId");

                    b.HasIndex("RouteSegmentId");

                    b.ToTable("RouteSegmentSectors");
                });

            modelBuilder.Entity("SlotRouteSegments", b =>
                {
                    b.Property<int>("RouteSegmentsId")
                        .HasColumnType("integer");

                    b.Property<int>("SlotId")
                        .HasColumnType("integer");

                    b.HasKey("RouteSegmentsId", "SlotId");

                    b.HasIndex("SlotId");

                    b.ToTable("SlotRouteSegments");
                });

            modelBuilder.Entity("CTPSimulator.Location", b =>
                {
                    b.HasBaseType("CTPSimulator.ThroughputPoint");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("VATSIMEventId")
                        .HasColumnType("integer");

                    b.HasIndex("VATSIMEventId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("CTPSimulator.RouteSegment", b =>
                {
                    b.HasBaseType("CTPSimulator.ThroughputPoint");

                    b.Property<string>("RouteSegmentGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("RouteSegmentTags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("RouteString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("VATSIMEventId")
                        .HasColumnType("integer");

                    b.HasIndex("VATSIMEventId");

                    b.ToTable("RouteSegments", (string)null);
                });

            modelBuilder.Entity("CTPSimulator.Sector", b =>
                {
                    b.HasBaseType("CTPSimulator.ThroughputPoint");

                    b.Property<string>("Coordinates")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("MaxLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxLongitude")
                        .HasColumnType("double precision");

                    b.Property<double>("MinLatitude")
                        .HasColumnType("double precision");

                    b.Property<double>("MinLongitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("VATSIMEventId")
                        .HasColumnType("integer");

                    b.HasIndex("VATSIMEventId");

                    b.ToTable("Sectors", (string)null);
                });

            modelBuilder.Entity("CTPSimulator.Airport", b =>
                {
                    b.HasBaseType("CTPSimulator.Location");

                    b.Property<DateTime>("DepartureTimeWindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumberOfVotes")
                        .HasColumnType("integer");

                    b.Property<int?>("VATSIMEventId1")
                        .HasColumnType("integer");

                    b.HasIndex("VATSIMEventId1");

                    b.ToTable("Airports", (string)null);
                });

            modelBuilder.Entity("CTPSimulator.Slot", b =>
                {
                    b.HasOne("CTPSimulator.Airport", "ArrivalAirport")
                        .WithMany()
                        .HasForeignKey("ArrivalAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTPSimulator.Airport", "DepartureAirport")
                        .WithMany()
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTPSimulator.ThroughputPoint", null)
                        .WithMany("SlotsAnalysisFrames")
                        .HasForeignKey("ThroughputPointId");

                    b.HasOne("CTPSimulator.VATSIMEvent", null)
                        .WithMany("Slots")
                        .HasForeignKey("VATSIMEventId");

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");
                });

            modelBuilder.Entity("CTPSimulator.VATSIMEvent", b =>
                {
                    b.OwnsOne("CTPSimulator.SimulatorCalculationParameters", "CalculationParameters", b1 =>
                        {
                            b1.Property<int>("VATSIMEventId")
                                .HasColumnType("integer");

                            b1.Property<double>("DepartureTimeWindowOffsetSynchronizationLongitude")
                                .HasColumnType("double precision");

                            b1.Property<string>("IntendedSlotGenerationMode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("RecalculateMaximumAirportSlots")
                                .HasColumnType("boolean");

                            b1.Property<bool>("ShouldSimulationUseActualWeatherForecastData")
                                .HasColumnType("boolean");

                            b1.Property<TimeSpan>("SimulationAnalysisResolution")
                                .HasColumnType("interval");

                            b1.Property<string>("SimulationOutputCommentary")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SlotGenerationOutputCommentary")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("VATSIMEventId");

                            b1.ToTable("VATSIMEvents");

                            b1.WithOwner()
                                .HasForeignKey("VATSIMEventId");
                        });

                    b.Navigation("CalculationParameters")
                        .IsRequired();
                });

            modelBuilder.Entity("RouteSegmentLocations", b =>
                {
                    b.HasOne("CTPSimulator.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTPSimulator.RouteSegment", null)
                        .WithMany()
                        .HasForeignKey("RouteSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RouteSegmentSectors", b =>
                {
                    b.HasOne("CTPSimulator.Sector", null)
                        .WithMany()
                        .HasForeignKey("ProvidedFacilityProgressionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTPSimulator.RouteSegment", null)
                        .WithMany()
                        .HasForeignKey("RouteSegmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SlotRouteSegments", b =>
                {
                    b.HasOne("CTPSimulator.RouteSegment", null)
                        .WithMany()
                        .HasForeignKey("RouteSegmentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTPSimulator.Slot", null)
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CTPSimulator.Location", b =>
                {
                    b.HasOne("CTPSimulator.ThroughputPoint", null)
                        .WithOne()
                        .HasForeignKey("CTPSimulator.Location", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTPSimulator.VATSIMEvent", null)
                        .WithMany("Waypoints")
                        .HasForeignKey("VATSIMEventId");
                });

            modelBuilder.Entity("CTPSimulator.RouteSegment", b =>
                {
                    b.HasOne("CTPSimulator.ThroughputPoint", null)
                        .WithOne()
                        .HasForeignKey("CTPSimulator.RouteSegment", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTPSimulator.VATSIMEvent", null)
                        .WithMany("RouteSegments")
                        .HasForeignKey("VATSIMEventId");
                });

            modelBuilder.Entity("CTPSimulator.Sector", b =>
                {
                    b.HasOne("CTPSimulator.ThroughputPoint", null)
                        .WithOne()
                        .HasForeignKey("CTPSimulator.Sector", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTPSimulator.VATSIMEvent", null)
                        .WithMany("Sectors")
                        .HasForeignKey("VATSIMEventId");
                });

            modelBuilder.Entity("CTPSimulator.Airport", b =>
                {
                    b.HasOne("CTPSimulator.Location", null)
                        .WithOne()
                        .HasForeignKey("CTPSimulator.Airport", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CTPSimulator.VATSIMEvent", null)
                        .WithMany("Airports")
                        .HasForeignKey("VATSIMEventId1");
                });

            modelBuilder.Entity("CTPSimulator.ThroughputPoint", b =>
                {
                    b.Navigation("SlotsAnalysisFrames");
                });

            modelBuilder.Entity("CTPSimulator.VATSIMEvent", b =>
                {
                    b.Navigation("Airports");

                    b.Navigation("RouteSegments");

                    b.Navigation("Sectors");

                    b.Navigation("Slots");

                    b.Navigation("Waypoints");
                });
#pragma warning restore 612, 618
        }
    }
}
